import type { Config } from "tailwindcss";

export default {
  content: ["app/**/*.tsx", "app/panel/index.html"],
  darkMode: ["class"],
  mode: "jit",
  theme: {
    spacing: {
      0: "0px",
      px: "1px",
      0.5: "calc(var(--spacing) * 0.5)",
      1: "var(--spacing)",
      1.5: "calc(var(--spacing) * 1.5)",
      2: "calc(var(--spacing) * 2)",
      2.5: "calc(var(--spacing) * 2.5)",
      3: "calc(var(--spacing) * 3)",
      3.5: "calc(var(--spacing) * 3.5)",
      4: "calc(var(--spacing) * 4)",
      5: "calc(var(--spacing) * 5)",
      6: "calc(var(--spacing) * 6)",
      7: "calc(var(--spacing) * 7)",
      8: "calc(var(--spacing) * 8)",
      9: "calc(var(--spacing) * 9)",
      10: "calc(var(--spacing) * 10)",
      11: "calc(var(--spacing) * 11)",
      12: "calc(var(--spacing) * 12)",
      14: "calc(var(--spacing) * 14)",
      16: "calc(var(--spacing) * 16)",
      20: "calc(var(--spacing) * 20)",
      24: "calc(var(--spacing) * 24)",
      28: "calc(var(--spacing) * 28)",
      32: "calc(var(--spacing) * 32)",
      36: "calc(var(--spacing) * 36)",
      40: "calc(var(--spacing) * 40)",
      44: "calc(var(--spacing) * 44)",
      48: "calc(var(--spacing) * 48)",
      52: "calc(var(--spacing) * 52)",
      56: "calc(var(--spacing) * 56)",
      60: "calc(var(--spacing) * 60)",
      64: "calc(var(--spacing) * 64)",
      72: "calc(var(--spacing) * 72)",
      80: "calc(var(--spacing) * 80)",
      96: "calc(var(--spacing) * 96)",
    },
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        sidebar: "var(--sidebar)",
        sidebarForeground: "var(--sidebar-foreground)",
        sidebarBorder: "var(--sidebar-border)",
        sidebarBackground: "var(--sidebar-background)",
        sidebarBackgroundHover: "var(--sidebar-background-hover)",
        sidebarBackgroundActive: "var(--sidebar-background-active)",
        sidebarBackgroundSelected: "var(--sidebar-background-selected)",
        sidebarBackgroundSelectedHover: "var(--sidebar-background-selected-hover)",
        sidebarBackgroundSelectedActive: "var(--sidebar-background-selected-active)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: "var(--font-sans)",
        serif: "var(--font-serif)",
        mono: "var(--font-mono)",
      },
      letterSpacing: {
        normal: "var(--tracking-normal)",
      },
      boxShadow: {
        "2xs": "var(--shadow-2xs)",
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
      },
    },
  },
  plugins: [],
} satisfies Config;
