const DISPLAY = {
  DASHBOARD: "DASHBOARD",
  CALENDAR: "CALENDAR",
  PROFILE: "PROFILE",
  STATS: "STATS",
  LOOT: "LOOT",
  ITEMS: "ITEMS",
  CALCULATOR: "CALCULATOR",
  HISTORY: "HISTORY",
  SETTINGS: "SETTINGS",
  DATA_VIEW: "DATA_VIEW",
};

export default DISPLAY;
